FROM debian:buster                                                                                                                                                                                                                              
                                     
WORKDIR /MP

COPY MP-surrogate.exe /MP/
COPY script.sh /MP/


ENTRYPOINT [ "bash", "/MP/script.sh" ]


